###########################################################
## Playbook to install and set up Minio on a single host ##
###########################################################
#
# REQUIREMENTS:
# - Install the required ansible roles. 
#       $ ansible-galaxy install -r requirements.yml --force
# - Sensitive credentials should be saved under an ansible vault protected yml in './vars'.
# 
# RUNNING THIS PLAYBOOK:
#  
#  $ ansible-playbook -i ../disslab/hosts --private-key ~/.ssh/ansible-user -u ansible-user playbook_example.yml
#
# NOTES:
#
#  - Tested against Fedora Server 36.
#  - The Minio root password _MUST_ be 8 characters or longer.

- name: Install Minio storage server
  become: yes
  gather_facts: yes
  hosts: minio
  roles:
    - joedissmeyer.ansible_role_minio
  vars:
    minio_root_user: minioadmin
    minio_root_password: minioadmin
    minio_server_download_source: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    minio_client_download_source: "https://dl.min.io/client/mc/release/linux-amd64/mc"