---

- name: Configure firewall ports for Minio S3 API and Minio Console UI
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ minio_server_port }}/tcp"
    - "{{ minio_console_port }}/tcp"

- name: Create the minio user group
  group:
    name: "{{ minio_root_user }}"
    state: present

- name: Create the minio user account
  user:
    name: "{{ minio_root_user }}"
    state: present
    group: "{{ minio_group }}"

- name: Ensure that minio directories are created
  file:
    path: '{{ minio_dir }}'
    state: directory
    mode: 0750
    owner: '{{ minio_root_user }}'
    group: '{{ minio_group }}'
  loop:
    - '{{ minio_home }}'
    - '{{ minio_home }}/bin'
    - '{{ minio_data_path }}'
    - '{{ minio_home }}/.minio'
    - '{{ minio_home }}/.minio/certs'
    - '{{ minio_data_path }}/.minio.sys'
    - '{{ minio_data_path }}/.minio.sys/config'
  loop_control:
    loop_var: minio_dir

- name: download and install minio server binary
  get_url:
    url: '{{ minio_server_download_source }}'
    dest: '{{ minio_home }}/bin/minio'
    mode: +x
    owner: '{{ minio_root_user }}'
    group: '{{ minio_group }}'
  register: file_downloaded
  retries: 15
  delay: 5
  until: file_downloaded is succeeded

- name: download and install minio client (mc)
  get_url:
    url: '{{ minio_client_download_source }}'
    dest: /usr/sbin/mc
    mode: +x
    owner: root
    group: root
  register: file_downloaded
  retries: 15
  delay: 5
  until: file_downloaded is succeeded