---
- include_tasks: install.yml
#- include_tasks: setup.yml

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Ensure Minio is started and enabled on boot.
  service:
    name: minio
    state: restarted
    enabled: True